### ISSUE TITLE
Can't find the integration in HACS

### ISSUE THREAD

**Issue by kuro-codes** [ivanmihov/homeassistant-ntfy.sh#2]
Really happy to have found this integration but sadly i can't add it via HACS. It can not be found when searching for repositories.

**Comment by ivanmihov** [comment]
The integration is not part of the default HACS repositories. Please follow the documentation on the HACS site to add it as a custom repo:
[https://hacs.xyz/docs/faq/custom_repositories](https://hacs.xyz/docs/faq/custom_repositories)
