### ISSUE TITLE
not a valid addon repository

### ISSUE THREAD

**Issue by mat-l** [ivanmihov/homeassistant-ntfy.sh#3]
HI @ivanmihov,
I am looking forward to connect my home assistant with your Ntfy.sh extension, but while adding your repository to my home assistant it complains, that it is not a vaild add-on repo. I would prefer to pull it directly from your repo instead of manual zip files to get future updates as well.
Any idea how to fix this?
Thank you for your work and sharing the add-on and all the best

![Screenshot_20230820_140202_io homeassistant companion android minimal](https://github.com/ivanmihov/homeassistant-ntfy.sh/assets/5571947/b85ac99d-ccdf-4a03-b641-27abde78cade)
![Screenshot_20230820_140210_io homeassistant companion android minimal](https://github.com/ivanmihov/homeassistant-ntfy.sh/assets/5571947/a189dbd5-6b84-424e-90de-413731cd57f4)

**Comment by DeflateAwning** [comment]
Follow the recommended install instructions in the README using HACS

**Comment by mat-l** [comment]
Sorry didn't know HACS until last week. ✌🏽
